language: python

python:
  - "3.6"
    
cache: pip

install:
  - pip install -r requirements.txt


script:
  - python manage.py quizModule/test_models.py
  - python manage.py quizModule/test_views.py