language: python

python:
  - "3.6"
    
cache: pip

install:
  - pip install -r requirements.txt
  - pip install serializers


script:
  - python quizModule/test_models.py
  - python quizModule/test_views.py