# Generated by Django 2.2 on 2019-04-08 16:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20)),
                ('programming_language', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('C++', 'C++'), ('C', 'C'), ('C#', 'C#'), ('JavaScript', 'JavaScript'), ('PHP', 'PHP'), ('Prolog', 'Prolog'), ('MySQL', 'MySQL'), ('TensorFlow', 'TensorFlow')], default='Python', max_length=30)),
                ('Programming_Type', models.CharField(choices=[('declarative', 'declarative'), ('procedural', 'procedural')], default='procedural', max_length=10)),
                ('skill_type', models.TextField(default='')),
                ('no_of_questions', models.IntegerField(default=3)),
                ('expected_duration', models.DurationField(default=datetime.timedelta(seconds=900))),
                ('Score_Point', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name_plural': 'quizzes',
            },
        ),
        migrations.CreateModel(
            name='Tagroba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e', models.CharField(blank=True, default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=2000)),
                ('Answer', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd'), ('e', 'e')], default='a', max_length=2)),
                ('a', models.CharField(blank=True, default='', max_length=2000)),
                ('b', models.CharField(blank=True, default='', max_length=2000)),
                ('c', models.CharField(blank=True, default='', max_length=2000)),
                ('d', models.CharField(blank=True, default='', max_length=2000)),
                ('e', models.CharField(blank=True, default='', max_length=2000)),
                ('quiz_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizModule.Quiz')),
            ],
        ),
    ]
