# Generated by Django 2.2 on 2019-04-08 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizModule', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tagroba',
            new_name='Tagrobat',
        ),
    ]
