# Generated by Django 2.2 on 2019-04-08 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizModule', '0002_auto_20190408_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagrobat',
            name='created_at',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagrobat',
            name='updated_at',
            field=models.TimeField(auto_now=True),
        ),
    ]
