# Generated by Django 2.2 on 2019-04-08 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizModule', '0003_auto_20190408_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagrobat',
            name='quiz_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizModule.Quiz'),
        ),
    ]
