# Generated by Django 2.2 on 2019-04-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizModule', '0005_solved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solved',
            old_name='quiz_id',
            new_name='quiz',
        ),
        migrations.RenameField(
            model_name='solved',
            old_name='user_id',
            new_name='user',
        ),
    ]
