# Generated by Django 2.2 on 2019-04-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizModule', '0007_remove_quiz_score_point'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tagrobat',
        ),
    ]
