# Generated by Django 2.2 on 2019-04-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizModule', '0010_auto_20190409_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz_id',
            field=models.ManyToManyField(to='quizModule.Quiz'),
        ),
    ]
