# Generated by Django 2.2 on 2019-04-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizModule', '0012_quiz_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
