# Generated by Django 2.2 on 2019-04-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizModule', '0013_auto_20190410_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(default='', max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='no_of_questions',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='score',
            field=models.IntegerField(default=0, editable=False, null=True),
        ),
    ]
